// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTZieeO73ICpOLkWbBBZJmBWO2AjCaGlE',
    appId: '1:943729907199:web:5a7d360fb30d24e62583ca',
    messagingSenderId: '943729907199',
    projectId: 'ecommerce-clone-7b05c',
    authDomain: 'ecommerce-clone-7b05c.firebaseapp.com',
    storageBucket: 'ecommerce-clone-7b05c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7MIFfnkwCqW158J_OajuhjA8oyhEVMrk',
    appId: '1:943729907199:android:97c2d7d7093fd9462583ca',
    messagingSenderId: '943729907199',
    projectId: 'ecommerce-clone-7b05c',
    storageBucket: 'ecommerce-clone-7b05c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEvi-B-irY3E714nW_2-Lp2Ra9wS-FUb8',
    appId: '1:943729907199:ios:056e98aa92110ee42583ca',
    messagingSenderId: '943729907199',
    projectId: 'ecommerce-clone-7b05c',
    storageBucket: 'ecommerce-clone-7b05c.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEvi-B-irY3E714nW_2-Lp2Ra9wS-FUb8',
    appId: '1:943729907199:ios:056e98aa92110ee42583ca',
    messagingSenderId: '943729907199',
    projectId: 'ecommerce-clone-7b05c',
    storageBucket: 'ecommerce-clone-7b05c.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTZieeO73ICpOLkWbBBZJmBWO2AjCaGlE',
    appId: '1:943729907199:web:45a79666a20a75e12583ca',
    messagingSenderId: '943729907199',
    projectId: 'ecommerce-clone-7b05c',
    authDomain: 'ecommerce-clone-7b05c.firebaseapp.com',
    storageBucket: 'ecommerce-clone-7b05c.firebasestorage.app',
  );
}
