name: getx_clean_default
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  get_it: ^7.6.4
  intl: ^0.18.1
  floor: ^1.4.2
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  dio: ^5.3.3
  retrofit: ^4.0.3
  logger: ^2.0.2+1
  awesome_dio_interceptor: ^1.0.0
  sqflite: ^2.3.0
  ionicons: ^0.2.2

dev_dependencies: 
  build_runner: ^2.4.6
  floor_generator: ^1.4.2
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.2

flutter: 
  uses-material-design: true

