name: flutter_to_do_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  flutter_local_notifications: ^15.1.0+1
  rxdart: ^0.27.7
  flutter_native_timezone: ^2.0.0
  timezone: ^0.9.2
  intl: ^0.18.1
  google_fonts: ^5.1.0
  date_picker_timeline: ^1.2.5
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

