name: ecommerce_clone
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ^3.7.2

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8

    firebase_auth:
    firebase_core:
    cloud_firestore:
    flutter_svg:
    flutter_bloc:
    dartz:
    get_it:
    desktop_window:
    shared_preferences:

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true

    assets:
      - assets/fonts/
      - assets/vectors/
      - assets/images/

    fonts:
      - family: CircularStd
        fonts:
          - asset: assets/fonts/CircularStd-Black.ttf
            weight: 800
          - asset: assets/fonts/CircularStd-Bold.ttf
            weight: 700
          - asset: assets/fonts/CircularStd-Medium.ttf
            weight: 500
          - asset: assets/fonts/CircularStd-Regular.ttf
            weight: 400