name: ecommerce_clone
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ^3.7.2

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8

    firebase_auth: ^5.3.1
    firebase_core: ^3.6.0
    cloud_firestore: ^5.4.4
    flutter_svg: ^2.0.10+1
    flutter_bloc: ^8.1.6
    dartz: ^0.10.1
    get_it: ^7.7.0
    desktop_window: ^0.4.0
    shared_preferences: ^2.3.2
    flutter_screenutil: ^5.9.3

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true

    assets:
      - assets/fonts/
      - assets/vectors/
      - assets/images/

    fonts:
      - family: CircularStd
        fonts:
          - asset: assets/fonts/CircularStd-Black.ttf
            weight: 800
          - asset: assets/fonts/CircularStd-Bold.ttf
            weight: 700
          - asset: assets/fonts/CircularStd-Medium.ttf
            weight: 500
          - asset: assets/fonts/CircularStd-Regular.ttf
            weight: 400