// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUCFGqy5ihnXzCqXu6TiSGw-tubGKz1LA',
    appId: '1:837238800150:android:bb283b6b5a87717e5f5a37',
    messagingSenderId: '837238800150',
    projectId: 'test-firebase-analytics-890f5',
    storageBucket: 'test-firebase-analytics-890f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyH5qiMnDktu2gLp2_6DOHJHE_ba89haE',
    appId: '1:837238800150:ios:d5dffbfe6dfbf7ee5f5a37',
    messagingSenderId: '837238800150',
    projectId: 'test-firebase-analytics-890f5',
    storageBucket: 'test-firebase-analytics-890f5.appspot.com',
    iosClientId: '837238800150-ns06jtdofchj1lj8jtkjlggk3lku2mcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFirebaseAnalytics',
  );
}
