name: clean_architecture
version: 1.0.0+1
publish_to: none
description: A new Flutter project for clean architecture
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: ^5.3.2
  retrofit: ^4.0.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  intl: ^0.18.1
  floor: ^1.4.2
  flutter_hooks: ^0.20.1
  cached_network_image: ^3.2.3
  google_fonts: ^6.1.0
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.8
  floor_generator: ^1.4.2

flutter:
  uses-material-design: true

