// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo8jWOeI_Y5De7ny3hOj5q6nQ7BeqerQ0',
    appId: '1:1064514469246:web:ad962029ad69df56b7872f',
    messagingSenderId: '1064514469246',
    projectId: 'spotify-clone-57f60',
    authDomain: 'spotify-clone-57f60.firebaseapp.com',
    storageBucket: 'spotify-clone-57f60.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsiOj0w0rKdq9fhXQB0Ss0ltaNW_Shpu0',
    appId: '1:1064514469246:android:37362db8bad27f6cb7872f',
    messagingSenderId: '1064514469246',
    projectId: 'spotify-clone-57f60',
    storageBucket: 'spotify-clone-57f60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6OF6lIGq7fiu2VmJwiVoqgtJ0_zzcpWQ',
    appId: '1:1064514469246:ios:1e39be999a670244b7872f',
    messagingSenderId: '1064514469246',
    projectId: 'spotify-clone-57f60',
    storageBucket: 'spotify-clone-57f60.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6OF6lIGq7fiu2VmJwiVoqgtJ0_zzcpWQ',
    appId: '1:1064514469246:ios:1e39be999a670244b7872f',
    messagingSenderId: '1064514469246',
    projectId: 'spotify-clone-57f60',
    storageBucket: 'spotify-clone-57f60.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo8jWOeI_Y5De7ny3hOj5q6nQ7BeqerQ0',
    appId: '1:1064514469246:web:d4c363010dbd564eb7872f',
    messagingSenderId: '1064514469246',
    projectId: 'spotify-clone-57f60',
    authDomain: 'spotify-clone-57f60.firebaseapp.com',
    storageBucket: 'spotify-clone-57f60.firebasestorage.app',
  );
}
